# ---------------
# Mock providers
# ---------------
mock_provider "aws" {
  # This is used because the mocked data is a random string instead of JSON, causing downstream dependencies to fail.
  # This block overrides the "json" output of ALL aws_iam_policy_document data blocks to use a JSON encoded string.
  mock_data "aws_iam_policy_document" {
    defaults = {
      json = "{\"some_fake\":\"json\"}"
    }
  }
  # This is used to return valid zone names for the us-west-2 zone instead of the random strings that Terraform will
  # generate for mocked tests. Not using this will cause the data block to create an empty list of strings.
  mock_data "aws_availability_zones" {
    defaults = {
      names = ["us-west-2a", "us-west-2b", "us-west-2c", "us-west-2d"]
    }
  }
}

# A mocked databricks provider is added here so that the alias requirement can be met
mock_provider "databricks" {
  alias = "mws"

  # This is used to return valid JSON for the data types of the assume role policy.
  mock_data "databricks_aws_assume_role_policy" {
    defaults = {
      json = "{\"some_fake\":\"json\"}"
    }
  }

}
# ---------------

# ---------------
# Variables
# ---------------
# The variables block below provides variable values for the configuration in this directory (tf/aws/variables.tf).
# Note that the below values were generated by AI, and are not real values.

variables {
  # Required variables
  aws_account_id                    = "123456789012"
  databricks_account_id             = "12345678-90ab-cdef-1234-567890abcdef"
  region                            = "us-west-2"
  resource_prefix                   = "my-databricks-dev"
  admin_user                        = "workspace-admin@example.com"
  audit_log_delivery_exists         = false
  enable_security_analysis_tool     = false
  metastore_exists                  = false
  network_configuration             = "isolated"
  vpc_cidr_range                    = "10.0.0.0/16"
  private_subnets_cidr              = ["10.0.1.0/24", "10.0.2.0/24"]
  privatelink_subnets_cidr          = ["10.0.3.0/24", "10.0.4.0/24"]
  public_subnets_cidr               = ["10.0.5.0/24", "10.0.6.0/24"]
  firewall_subnets_cidr             = ["10.0.7.0/24", "10.0.8.0/24"]
  sg_egress_ports                   = ["443", "3306", "6666"]
  cmk_admin_arn                     = "arn:aws:iam::123456789012:role/DatabricksCMKAdmin"
  deployment_name                   = "my-databricks-workspace"
  compliance_standards              = ["PCI_DSS"]
  create_service_direct_vpce        = false
  custom_vpc_id                     = null
  custom_private_subnet_ids         = null
  custom_sg_id                      = null
  custom_general_access_vpce_id     = null
  custom_scc_relay_vpce_id          = null
  custom_service_direct_vpce_id     = null
  custom_general_access_mws_vpce_id = null
  custom_scc_relay_mws_vpce_id      = null
  custom_service_direct_mws_vpce_id = null
  workspace_display_name            = null
  custom_metastore_name             = null

  # New variables for GovCloud support
  databricks_gov_shard     = null
  aws_partition            = null
  databricks_provider_host = null
}

# ---------------
# Tests
# ---------------
# This runs a plan command on the module directly
run "plan_test" {
  command = plan
}

# Plans with the optional security features enabled, since the default run leaves them all off:
# automatic cluster update, compliance security profile, enhanced security monitoring, account-level
# disable of legacy features, IP-based ingress restriction, the security analysis tool, and serverless private
# endpoint rules.
run "plan_test_full_features" {
  command = plan

  variables {
    context_based_ingress_ip_acl                  = ["203.0.113.0/24"]
    cross_workspace_ingress_allowed_workspace_ids = [1234567890123456]
    disable_legacy_features_at_account_level      = true
    enable_automatic_cluster_update               = true
    enable_compliance_security_profile            = true
    enable_enhanced_security_monitoring           = true
    enable_security_analysis_tool                 = true
    serverless_private_endpoint_rules = [
      {
        endpoint_service = "com.amazonaws.vpce.us-west-2.vpce-svc-0123456789abcdef0"
        domain_names     = ["db.internal.example.com"]
      },
      {
        resource_names = ["my-example-bucket"]
      },
    ]
  }
}

# Plans a custom network that brings its own VPC, subnets, security group, and AWS VPC endpoints.
run "plan_test_custom_network" {
  command = plan

  variables {
    custom_general_access_vpce_id = "vpce-0abcd1234efgh5678"
    custom_private_subnet_ids     = ["subnet-0abcd1234efgh5678", "subnet-1abcd1234efgh5678"]
    custom_scc_relay_vpce_id      = "vpce-1abcd1234efgh5678"
    custom_sg_id                  = "sg-0abcd1234efgh5678"
    custom_vpc_id                 = "vpc-0abcd1234efgh5678"
    network_configuration         = "custom"
  }
}

# Plans a custom network whose endpoints are already registered with Databricks, so the Databricks-side
# VPC endpoint IDs are supplied in place of the AWS VPC endpoint IDs.
run "plan_test_custom_network_registered_endpoints" {
  command = plan

  variables {
    custom_general_access_mws_vpce_id = "11111111-2222-3333-4444-555555555555"
    custom_private_subnet_ids         = ["subnet-0abcd1234efgh5678", "subnet-1abcd1234efgh5678"]
    custom_scc_relay_mws_vpce_id      = "66666666-7777-8888-9999-000000000000"
    custom_sg_id                      = "sg-0abcd1234efgh5678"
    custom_vpc_id                     = "vpc-0abcd1234efgh5678"
    network_configuration             = "custom"
  }
}

# Plans a Service Direct endpoint in us-west-2, where Service Direct supports only some AZs, so the intra subnets
# are looked up to filter by AZ. The filtered subnet IDs are only known at apply, since the subnets are created in
# the same plan.
run "plan_test_service_direct_limited_az_region" {
  command = plan

  variables {
    create_service_direct_vpce = true
  }

  assert {
    condition     = length(aws_vpc_endpoint.service_direct) == 1 && length(data.aws_subnet.intra) == 2
    error_message = "The Service Direct endpoint must be created and the intra subnets looked up in a limited-AZ region."
  }
}

# Plans a Service Direct endpoint in us-east-2, which supports every AZ, so no subnet lookup is needed.
run "plan_test_service_direct_all_az_region" {
  command = plan

  variables {
    create_service_direct_vpce = true
    region                     = "us-east-2"
  }

  assert {
    condition     = length(aws_vpc_endpoint.service_direct) == 1 && length(data.aws_subnet.intra) == 0
    error_message = "The Service Direct endpoint must be created without looking up subnet AZs in an all-AZ region."
  }
}

# The default plan leaves Service Direct off, so the subnet AZ lookup must not run.
run "plan_test_service_direct_off_skips_subnet_lookup" {
  command = plan

  assert {
    condition     = length(aws_vpc_endpoint.service_direct) == 0 && length(data.aws_subnet.intra) == 0
    error_message = "The intra subnet AZ lookup must be skipped when Service Direct is off."
  }
}

# A custom network with none of its required inputs must be rejected by the network_configuration validations
# rather than failing later on missing VPC, security group, or endpoint resources.
run "custom_network_missing_inputs_rejected" {
  command = plan

  variables {
    network_configuration = "custom"
  }

  expect_failures = [
    var.network_configuration,
  ]
}

# HYBRID mode creates AWS resources whose ARNs embed the account ID, so a missing aws_account_id must be
# rejected by its validation rather than failing later on null values in IAM policy templates.
run "hybrid_missing_aws_account_id_rejected" {
  command = plan

  variables {
    aws_account_id = null
  }

  expect_failures = [
    var.aws_account_id,
  ]
}

# An empty aws_account_id (as left in template.tfvars.example) counts as missing in HYBRID mode.
run "hybrid_empty_aws_account_id_rejected" {
  command = plan

  variables {
    aws_account_id = ""
  }

  expect_failures = [
    var.aws_account_id,
  ]
}

# An aws_account_id that is not a 12-digit ID (here, a pasted ARN) must be rejected before it reaches IAM ARNs.
run "malformed_aws_account_id_rejected" {
  command = plan

  variables {
    aws_account_id = "arn:aws:iam::123456789012:root"
  }

  expect_failures = [
    var.aws_account_id,
  ]
}
# ---------------
