import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// };

// const sidebars = {
//   tutorialSidebar: [
//     'overview',
//     {
//       type: 'category',
//       label: 'Usage',
//       link: { type: 'doc', id: 'usage/index' },
//       collapsible: true,
//       collapsed: false,
//       items: [
//         {
//           type: 'category',
//           label: 'AWS',
//           link: { type: 'doc', id: 'usage/AWS/index' },
//         },
//         {
//           type: 'category',
//           label: 'Azure',
//           link: { type: 'doc', id: 'usage/Azure/index' },
//         },
//         {
//           type: 'category',
//           label: 'GCP',
//           link: { type: 'doc', id: 'usage/GCP/index' },
//         },
//       ],
//     },
//     'troubleshooting',
//   ],
// };

const sidebars = {
  tutorialSidebar: [
    'overview',
    {
      type: 'category',
      label: 'Usage',
      link: { type: 'doc', id: 'usage/index' },
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'AWS',
          link: { type: 'doc', id: 'usage/AWS/index' },
          collapsible: true,
          collapsed: true,
          items: [
            { type: 'doc', id: 'usage/AWS/preread', label: 'Read Before Deploying' },
            { type: 'doc', id: 'usage/AWS/components', label: 'SRA Components Breakdown' },
            { type: 'doc', id: 'usage/AWS/gettingstarted', label: 'Getting Started' },
            { type: 'doc', id: 'usage/AWS/awsgovcloud', label: 'AWS GovCloud' },
          ],
        },
        {
          type: 'category',
          label: 'Azure',
          link: { type: 'doc', id: 'usage/Azure/index' },
          collapsible: true,
          collapsed: true,
          items: [
            { type: 'doc', id: 'usage/Azure/preread', label: 'Read Before Deploying' },
            { type: 'doc', id: 'usage/Azure/components', label: 'SRA Components Breakdown' },
            { type: 'doc', id: 'usage/Azure/gettingstarted', label: 'Getting Started' },
            {
              type: 'category',
              label: 'Deployment Modes',
              link: { type: 'doc', id: 'usage/Azure/deploymentmodes' },
              collapsible: true,
              collapsed: false,
              items: [
                { type: 'doc', id: 'usage/Azure/mode1-full-sra', label: 'Mode 1: Full SRA' },
                { type: 'doc', id: 'usage/Azure/mode2-byo-hub', label: 'Mode 2: BYO Hub' },
                { type: 'doc', id: 'usage/Azure/mode3-byo-hub-spoke', label: 'Mode 3: BYO Hub + Spoke' },
              ]
            },
            { type: 'doc', id: 'usage/Azure/configuration', label: 'Configuration' },
            { type: 'doc', id: 'usage/Azure/troubleshooting', label: 'Troubleshooting' }
          ],
        },
        {
          type: 'category',
          label: 'GCP',
          link: { type: 'doc', id: 'usage/GCP/index' },
          collapsible: true,
          collapsed: true,
          items: [
            { type: 'doc', id: 'usage/GCP/preread', label: 'Read Before Deploying' },
            { type: 'doc', id: 'usage/GCP/components', label: 'SRA Components Breakdown' },
            { type: 'doc', id: 'usage/GCP/gettingstarted', label: 'Getting Started' }
          ],
        },
      ],
    },
    'additionalresources',
  ],
};

export default sidebars;

