name: Docs test deployment

defaults:
  run:
    working-directory: ./docs/sra

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
