# This workflow is used for testing the terraform-ruw reusable workflow.

name: Workflow Mock Tests
on:
  push:
    paths:
      - '.workflow-mock/**'
      - '.github/workflows/workflow-mock-test.yml'
      - '.github/workflows/terraform-ruw.yml'
  pull_request:
    paths:
      - '.workflow-mock/**'
      - '.github/workflows/workflow-mock-test.yml'
      - '.github/workflows/terraform-ruw.yml'
jobs:
  workflow-mock-test:
    uses: ./.github/workflows/terraform-ruw.yml
    with:
      working_directory: .workflow-mock
